# coding=utf-8
from datetime import date
from tempfile import TemporaryDirectory
from os import path

from django.core.management import BaseCommand
from django.core.files import File

from documentmanagement.utils import pdflatex
from usermanagement.utils import get_shackbureau_user


class Command(BaseCommand):

    help = "generate a paper letter for all members without a validated tracking code"

    def handle(self, *args, **options):
        from usermanagement.models import Member, MemberDocument, MemberDocumentTag

        template = "documentmanagement/letter.tex"
        content = """
        für den Abgleich deiner Mitgliedsdaten konnten wir dich per Email unter \\url{{{email}}} nicht erreichen.

        Bitte melde dich bei uns per Email unter \\url{{vorstad@shackspace.de}}, damit wir deine Daten abgleichen können.
        """
        opening = "Hallo {name},"
        subject = "Deine Mitgliedsdaten"
        filename = "membertracking_{date}_{id:04d}_{surname}_{name}"
        additional_files = (('static/img/logo_shack_brightbg.pdf', 'img/logo_shack_brightbg.pdf'), )

        shackbureau_user = get_shackbureau_user()
        today = date.today()
        tag, created = MemberDocumentTag.objects.get_or_create(tag="Membertracking",
                                                               defaults={"created_by": shackbureau_user})
        for member in Member.objects.filter(is_active=True)\
                                    .filter(membertrackingcode__validated=False):
            context = {'closing': "Mit freundlichen Grüßen",
                       'signature': "Der Vorstand",
                       'place': "Stuttgart",
                       'date': today,
                       'subject': subject,
                       'opening': opening.format(name=member.name),
                       'content': content.format(email=member.email),
                       'address': member.get_postal_address()
                       }

            base_filename = filename.format(date=today.isoformat(),
                                            id=member.member_id,
                                            surname=member.surname,
                                            name=member.name)

            with TemporaryDirectory() as tempdirectory:
                pdf = pdflatex(base_filename=base_filename,
                               template=template,
                               context=context,
                               tempdirectory=tempdirectory,
                               additional_files=additional_files)
                print(pdf)

                with open(pdf, 'rb') as f:
                    memberdocument = MemberDocument()
                    memberdocument.member = member
                    memberdocument.created_by = shackbureau_user
                    memberdocument.description = "Member tracking {}".format(today.isoformat())
                    memberdocument.comment = "autogenerated at {}".format(today.isoformat())
                    memberdocument.data_file.save(path.basename(pdf), File(f))
                    memberdocument.save()
                    memberdocument.tag.add(tag)
