# coding=utf-8
from datetime import date
from tempfile import TemporaryDirectory
from os import path

from django.core.management import BaseCommand
from django.core.files import File

from documentmanagement.utils import pdflatex
from usermanagement.utils import get_shackbureau_user
from usermanagement.models import Member, MemberDocument, MemberDocumentTag


class Command(BaseCommand):

    help = "generate a paper letter for all members without a validated tracking code"

    def add_arguments(self, parser):
        parser.add_argument('year', type=int)

    def handle(self, *args, **options):

        year = options['year']

        template = "documentmanagement/donationreceipt.tex"
        filename = "donationreceipt_{year}_{id:04d}_{surname}_{name}"
        additional_files = (('static/img/logo_shack_brightbg.pdf', 'img/logo_shack_brightbg.pdf'), )

        shackbureau_user = get_shackbureau_user()
        today = date.today()
        tag, created = MemberDocumentTag.objects.get_or_create(tag="Spendenbescheinigung",
                                                               defaults={"created_by": shackbureau_user})
        counter = 0
        for member in Member.objects.get_active_members_in_year(year):
            payed_membership_fee = member.get_payed_membership_fee(year)
            if payed_membership_fee <= 0:
                continue
            counter += 1
            context = {
                'place': "Stuttgart",
                'date': today,
                'address_of_donator': member.get_postal_address(),
                'amount': payed_membership_fee,
                'donation_type': 'allowance in money',
                'day_of_donation': year,
                'no_signature': True,
            }

            base_filename = filename.format(year=year,
                                            id=member.member_id,
                                            surname=member.surname,
                                            name=member.name)

            with TemporaryDirectory() as tempdirectory:
                pdf = pdflatex(base_filename=base_filename,
                               template=template,
                               context=context,
                               tempdirectory=tempdirectory,
                               additional_files=additional_files)

                with open(pdf, 'rb') as f:
                    memberdocument = MemberDocument()
                    memberdocument.member = member
                    memberdocument.created_by = shackbureau_user
                    memberdocument.description = "Spendenbescheinigung Mitgliedsbeitrag {}".format(year)
                    memberdocument.comment = "autogenerated at {}".format(today.isoformat())
                    memberdocument.data_file.save(path.basename(pdf), File(f))
                    memberdocument.save()
                    memberdocument.tag.add(tag)

            from django.core.mail import EmailMessage
            mail = EmailMessage('Zuwendungsbescheinigung über Mitgliedsbeiträge {year}'.format(year=year),
                                'Hallo {name},\n\nim Anhang ist deine Zuwendungsbescheinigung über deine Mitgliedsbeiträge an den shack e.V. für das Jahr {year}.\n\nder Vorstand'.format(name=member.name, year=year),
                                'vorstand@shackspace.de',
                                [member.email])
            mail.attach_file(memberdocument.data_file.path)
            sent = mail.send()
            if sent:
                memberdocument.comment += "\nsend per email to {email} at {date}".format(email=member.email,
                                                                                          date=today.isoformat())
                memberdocument.save()
                break

        print(counter)
