# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 21:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0058_auto_20160410_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlog',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
