# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0059_memberlog_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberspecials',
            name='has_laser_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberspecials',
            name='laserkey_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
